
#:set s dp(150)

<CanvasExample1>:
    canvas:
        Line:
            points: (0, 0, self.width/8, 100, self.width/4, 0, self.width*3/8,100, self.width*3/6, 0, self.width*3/5, 100, self.width*6/8, 0, self.width*5/6, 100, self.width, 0)
            width: 2
            
        Rectangle:
            pos: self.center_x - s/2 , self.center_y - s/2
            size: s, s
        Ellipse:
            pos: self.center_x - s/2, self.center_y + s
            size: s, s/2
